@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9obiBqb2huIiwicm9sZSI6IlVzZXIiLCJzdWIiOiIxIiwiaWF0IjoxNjAwMTg5NDkwLCJleHAiOjE2MDAxOTMwOTB9.Sjb86hJVKlbj5s9ummFK4S2c-Dvvq-SHIW9szLHoWVs

@accessToken = Bearer {{token}}



###############################################################################
#                                     AUTH                                    #
###############################################################################

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "a@b.c", "password": "changeme"
}

###

POST {{host}}/auth/signup
Content-Type: application/json

{
    "email": "raju6@b.com",
    "password": "!Abcd1234",
    "firstName": "New",
    "lastName": "New"
}

###

GET {{host}}/auth/verify?token=gQXJUjxM7rvGt7yPWEdQNx-XNJ2v1Odc

###


###############################################################################
#                                  PROFILE                                    #
###############################################################################

GET {{host}}/profile
Content-Type: application/json
Authorization: {{accessToken}}
