@hostname = localhost
@port = 3333
@host = http://{{hostname}}:{{port}}/api

@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTYwMDE3MTE5NSwiZXhwIjoxNjAwMTc0Nzk1fQ.9_WZi-Sl90k1u-6fP2wOuusd-MySneb1D5Nf6XmmPG0



###############################################################################
#                                     AUTH                                    #
###############################################################################

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "a@b.c", "password": "changeme"
}

###

GET {{host}}/profile
Content-Type: application/json
Authorization: {{accessToken}}